version: '3'
services:
  db:
    image: mariadb:10.6.5-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
  backend:
    build: back
    ports: 
      - 3334:8000
    secrets:
      - db-password
    depends_on:
      - db
  web:
    build: web
    ports:
      - 3335:80
    depends_on:
      - backend
    volumes:
      - ./web/src:/var/www/html
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
