version: '3'
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
  database:
    extends:
      file: docker-compose.yml
      service: database