version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: musicapp
    ports:
      - '5431:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/musicapp.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      # - './backend/:/usr/src/backend'   # Development
      - 'backend:/usr/src/backend'      # Production
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      # - './frontend/:/usr/src/frontend'   # Development
      - 'frontend:/usr/src/frontend'      # Production
    networks:
      - app-network

networks:
 app-network:
  driver: bridge

volumes:
  db:
    driver: local
  backend:
    driver: local
  frontend:
    driver: local
